{
 "title": "Telemetria - SSR grafana",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Servidor",
    "label": "Selecione o Servidor",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Selecione o servidor",
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Ambiente/SSR" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "% Memory Utilization - $Servidor",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "Ambiente/SSR" },
     "host": { "filter": "$Servidor" },
     "item": { "filter": "Memory utilization %" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "SWAP LIVRE - $Servidor",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "Ambiente/SSR" },
     "host": { "filter": "$Servidor" },
     "item": { "filter": "Free swap space in %" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Services - $Servidor",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Services" },
     "evaltype": "0",
     "group": { "filter": "Ambiente/SSR" },
     "host": { "filter": "$Servidor" },
     "item": { "filter": "/SERVICO.*/" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 8 },
   "options": { "content": "# <center>$Servidor</center>" },
   "targets": [
    {
     "application": { "filter": "General" },
     "group": {
      "filter": "Infraestrutura Oi/Windows Server"
     },
     "host": { "filter": "$Servidor" },
     "item": { "filter": "System name" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "% CPU utilization - $Servidor",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "Ambiente/SSR" },
     "host": { "filter": "$Servidor" },
     "item": { "filter": "CPU utilization" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "% Memory Utilization - $Servidor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "Ambiente/SSR" },
     "host": { "filter": "$Servidor" },
     "item": { "filter": "Memory utilization %" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Network interfaces - $Servidor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "Ambiente/SSR" },
     "host": { "filter": "$Servidor" },
     "item": { "filter": "/.*Bits received.*/" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "Network interfaces" },
     "group": {
      "filter": "Infraestrutura Oi/Windows Server"
     },
     "host": { "filter": "$Servidor" },
     "item": { "filter": "/.*Bits sent.*/" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Disponibilidade $Servidor",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Availability" },
     "group": { "filter": "Ambiente/SSR" },
     "host": { "filter": "$Servidor" },
     "item": { "filter": "ICMP ping" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "UpTime - $Servidor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Status" },
     "group": { "filter": "Ambiente/SSR" },
     "host": { "filter": "$Servidor" },
     "item": { "filter": "Uptime" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "% CPU utilization - $Servidor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "Ambiente/SSR" },
     "host": { "filter": "$Servidor" },
     "item": { "filter": "CPU utilization" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Espaço em Disco - $Servidor",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Disk" },
     "group": { "filter": "Ambiente/SSR" },
     "host": { "filter": "$Servidor" },
     "item": { "filter": "/.*Space utilization.*/" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "INCIDENTES ABERTOS NO ITSM - $Servidor",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  LTRIM(RTRIM(A.status)) AS Status,\r\n  a.PRIORIDADENUMERO AS Sev,\r\n  A.IncidentID,\r\n  a.Descricao,\r\n  a.DataCriacao,\r\n  a.DataResolvido,\r\n  CONCAT('incident/', a.INSTANCEID) AS INSTANCIA\r\nFROM\r\n  Dbo.HPD_INCIDENTINTERFACEview a\r\nWHERE\r\n  a.ClienteLoginID = 'IntegracaoTruesight'\r\n  AND UPPER(Descricao) LIKE CONCAT(\r\n    '%',\r\n    UPPER(\r\n      LEFT(\r\n        '$Servidor',\r\n        CASE\r\n          WHEN CHARINDEX('.', '$Servidor') > 0 THEN CHARINDEX('.', '$Servidor') - 1\r\n          ELSE LEN('$Servidor')\r\n        END\r\n      )\r\n    ),\r\n    '%'\r\n  )\r\n  AND DataCriacao >= '2023-06-01 11:13:42.000'\r\nORDER BY\r\n  DataCriacao DESC;"
    }
   ]
  }
 ]
}